/** 每个数据文件对应一个仓储实例（见 03 文档 5.2） */
export const HOME_REPOSITORY = Symbol('HOME_REPOSITORY');
export const ORGANIZATIONS_REPOSITORY = Symbol('ORGANIZATIONS_REPOSITORY');
export const CONTRIBUTIONS_REPOSITORY = Symbol('CONTRIBUTIONS_REPOSITORY');
export const WIKI_REPOSITORY = Symbol('WIKI_REPOSITORY');
export const CONTRIBUTORS_REPOSITORY = Symbol('CONTRIBUTORS_REPOSITORY');
export const SUMMITS_REPOSITORY = Symbol('SUMMITS_REPOSITORY');
export const MEETINGS_REPOSITORY = Symbol('MEETINGS_REPOSITORY');
/** 身份匹配控制台（写侧）：自然人档案 */
export const PERSONS_REPOSITORY = Symbol('PERSONS_REPOSITORY');
/** 身份匹配控制台（写侧）：身份认领映射边 */
export const IDENTITY_CLAIMS_REPOSITORY = Symbol('IDENTITY_CLAIMS_REPOSITORY');

export const ALL_REPOSITORY_TOKENS = [
  HOME_REPOSITORY,
  ORGANIZATIONS_REPOSITORY,
  CONTRIBUTIONS_REPOSITORY,
  WIKI_REPOSITORY,
  CONTRIBUTORS_REPOSITORY,
  SUMMITS_REPOSITORY,
  MEETINGS_REPOSITORY,
  PERSONS_REPOSITORY,
  IDENTITY_CLAIMS_REPOSITORY,
] as const;
